"""HTML report generator for VulnScanner."""
from pathlib import Path
from datetime import datetime

SEV_COLOR = {"CRITICAL": "#f85149", "HIGH": "#e67e22", "MEDIUM": "#f1c40f", "LOW": "#2ecc71", "INFO": "#58a6ff"}

def generate_html_report(results: dict, output_dir: str, scan_id: str) -> str:
    rows = ""
    for f in results["findings"]:
        c = SEV_COLOR.get(f["severity"], "#888")
        rows += f'<tr><td style="color:{c};font-weight:bold">{f["severity"]}</td><td>{f["category"]}</td><td>{f["name"]}</td><td>{f["detail"]}</td></tr>'

    html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>VulnScanner Report — {results['target']}</title>
<style>body{{font-family:Segoe UI,sans-serif;background:#0d1117;color:#c9d1d9;padding:32px}}
h1{{color:#f0f6fc}} table{{width:100%;border-collapse:collapse;background:#161b22;border-radius:8px}}
th{{background:#238636;color:#fff;padding:10px;text-align:left;font-size:13px}}
td{{padding:10px;border-bottom:1px solid #30363d;font-size:13px}}</style></head>
<body><h1>🔍 VulnScanner Report</h1>
<p style="color:#8b949e">Target: {results['target']} | Scan ID: {scan_id} | {results['timestamp'][:19]} | {results['total']} findings</p>
<table><thead><tr><th>Severity</th><th>Category</th><th>Finding</th><th>Detail</th></tr></thead>
<tbody>{rows}</tbody></table>
<p style="margin-top:24px;font-size:12px;color:#555">Generated by VulnScanner — Om Awachar</p></body></html>"""

    path = Path(output_dir) / f"report_{scan_id}.html"
    path.write_text(html)
    return str(path)
